name: build and deploy to DockerHub viethungdev23 

on:
  push:
    branches: 
      - main
  workflow_dispatch: 

jobs:
  build:   # tên job 
    runs-on: self-hosted  # run bằng host tự tạo của toi
    timeout-minutes: 5
    
    steps: # các step được thực hiện trong job 'build'
      - uses: actions/checkout@v4      # step 1 : kéo code từ repo github về runner
        
      - name: Setup .NET               # step 2 : cài đặt môi trường 
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '7.x' # Sửa đổi tương ứng với phiên bản .NET của bạn
          include-prerelease: true
          
      - name: Build                    # step 3 : build code 
        run: dotnet build --configuration Release
  
  deploy:  # tên job 
    runs-on: self-hosted
    needs: build      # cần yêu cầu job build phải chạy xong thì mới thực hiện deploy 

    steps: # các step được thực hiện trong job 'deploy'
      - uses: actions/checkout@v3      # step 1 : kéo code từ repo github về runner                   

      - name: Build and push Docker image    # step 2 : build code thành image theo cấu hình bên dưới ròi push lên dockerhub 
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: viethungdev23/dotnet-demo            # image
          tags: latest                                # image version
          registry: docker.io                         # registry url 
          dockerfile: Dockerfile                      # đường dẫn đến Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}    # username dockerhub 
          password: ${{ secrets.DOCKER_PASSWORD }}    # password 
